name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm Install
        with:
          python-version: 3.7
      - name: Lint
        run: npm run lint
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
